### ISSUE TITLE
Show specific warning if WASM is not supported by client

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/AliasVault#276]
Start chrome without WASM support in MacOS:

```
open /Applications/Google\ Chrome.app --args --js-flags=--noexpose_wasm
```

**Comment by flawrist** [comment]
I use Edge 109 on Windows 7 x64 and even cannot sign up because of WASM error.
It seems AliasVault is the only web-based password manager that has no workaround for this.

![](https://github.com/user-attachments/assets/4d592bb2-ba1e-437f-bb22-64a1fbf55e55)

**Comment by lanedirt** [comment]
Hi @sergeevabc, yes the AliasVault web app is built using WebAssembly, and requires that to be available in the browser that you are using in order to start. There is no workaround for this.

Also, Windows 7 and Edge 109 have been out of support since 2023. So you would either need to switch to another more modern browser (e.g. Chrome) and/or update your OS.

**Comment by flawrist** [comment]
@lanedirt 
A robust password manager must work on a wide variety of devices for as long as possible, relying solely on strong encryption, not on fleeting Silicon Valley trends. When you chase fashion over security, you build fragile apps that break tomorrow. For example, KeePass (which I have trusted for over 20 years) uses the older .NET Framework [3.5+](https://keepass.info/help/kb/sec_issues.html#netver) instead of .NET 10 because that version is sufficient to render the UI and handle I/O. This choice does not hurt security, but it allows people to keep secrets even in [favelas](https://en.wikipedia.org/wiki/Favela), thus making encryption a baseline rather than a luxury — much like a calculator or an alarm clock. If you step off the tourist paths and marketing hype to look at the real world, you'll see that people prefer not to upgrade [over and over again](https://en.wikipedia.org/wiki/Planned_obsolescence), but to use things that last — like a sturdy hammer that still drives nails after its factory closes. Web-based password managers such as Bitwarden, pCloud Pass, and Zoho Vault also work fine on legacy systems. That's why your focus on Mono WASM seems so short-sighted — it hinders widespread adoption and keeps the solution confined to a niche instead of helping a much broader audience.
