### ISSUE TITLE
Password Not correct

### ISSUE THREAD

**Issue by dumbu3** [lanedirt/AliasVault#460]
Hello, I just created an account on https://aliasvault.net, but when I try to log in in from a different browser, I get an Invalid username or password. Please try again. But the password is 100% correct. I even tried to change the password from the browser I was logged in into, but it says the current password provided is invalid. Please try again.
![Screenshot_1](https://github.com/user-attachments/assets/4a89b5a4-ba84-48c1-8503-378c3159f9a2)

**Comment by lanedirt** [comment]
Hi @dumbu3,

Thanks for creating an issue. The login logic is the same for unlocking your vault and all the other areas for logging in. As it works fine for other users I'm not sure what's going wrong in your case.

Are you 100% sure you are typing the correct username? I'm assuming you are but asking just in case.

Could you otherwise try to create a new account and see if you can reproduce the problem? I would gladly investigate this issue but I'm afraid it will be hard to debug as for everyone else it seems to work fine.

If you have more information to share or if you are able to reproduce this issue with perhaps some test credentials (username/password) please let me know.

**Comment by lanedirt** [comment]
Thanks for the video! I notice that you're using Bitwarden password autocomplete. Did you also try to type in a password manually?

There's no reason why it would not work with Bitwarden but perhaps there is a bug when the password is entered via autocomplete. I'll try to replicate the same behavior with the Bitwarden browser plugin tomorrow to see if I get the same results.

Thanks again for taking the time to report this issue, I'll get back to you.

**Comment by lanedirt** [comment]
Hi @dumbu3,

I investigated the issue and found out the cause was that when an account was created with capitalized (uppercase) letters the encryption key was not created correctly which caused issues when logging in at a later time. If a user was created with just lowercase letters in the username this problem did not occur. However this is quite a critical bug so thanks again for taking the time to report it! 

The bug is now fixed and I have also added feature tests to cover this usecase.

Version 0.9.3 is released and has been deployed to https://app.aliasvault.net which contains the fix.

Thanks again for taking the time to report this bug!
